/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.terasology.nui.samples.desktop;

import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import org.terasology.nui.samples.SamplesApp;

public class App {
    public static void main(String[] args) {
        Lwjgl3ApplicationConfiguration configuration = new Lwjgl3ApplicationConfiguration();
        configuration.setWindowedMode(1024, 768);
        configuration.setTitle("NUI Samples");
        new Lwjgl3Application(new SamplesApp(), configuration);
    }
}
